### ISSUE TITLE
Create a Vue Application

### ISSUE THREAD

**Issue by nelkor** [nelkor/passcryptum#1]
Необходимо инициализировать базу приложения Vue 3. Следует сделать это по [инструкции](https://vuejs.org/guide/quick-start.html#creating-a-vue-application). Из опциональных пунктов предлагаю добавить: TypeScript, Vitest, ESLint и Prettier. В остальном необходимости не вижу. В качестве favicon можно сразу поставить SVG-изображение ключа. В качестве title — имя репозитория с заглавной буквы. Весь лишний код, который создаётся при инициализации в качестве примера, необходимо удалить.

**Comment by VladislavBobyrev** [comment]
Согласен только от себя хотел бы добавить stylelint.

**Comment by nelkor** [comment]
Stylelint не является опциональным пунктом при инициализации приложения по данной инструкции. Он будет добавлен отдельно.

**Comment by nelkor** [comment]
Отличная работа, @VladislavBobyrev! 💪
