### ISSUE TITLE
Setting up git hook

### ISSUE THREAD

**Issue by VladislavBobyrev** [nelkor/passcryptum#18]
Предлогаю добавить клиентские прекоммит хуки.
 
Использовать при этом pre-commit пакета [Husky](https://github.com/typicode/husky) 

-  pre-commit  используется для проверки данных перед созданием коммита и позволяет увидеть если вы что-то забыли, запустить тесты, или выполнить другую необходимую проверку кода. Создание коммита будет отменено если выполнение хука завершится с ошибкой.

Добавить в pre-commit:
1. Запуск Eslint и Stylelint
2. Добавить форматирование кода PrettierOM

**Comment by nelkor** [comment]
В таком случае нам надо разделить в `package.json` команды проверки и форматирования.

Команда `npm run lint` будет только проверять код (ESLint + Stylelint без `--fix`). Эта команда будет использоваться в pre-commit хуке.

Команда `npm run fix` будет исправлять найденные проблемы (ESLint + Stylelint с `--fix`). Prettier вообще можно убрать из этих команд.

**Comment by VladislavBobyrev** [comment]
А зачем проверятьть есть ли ошибки, если можно сразу их исправить?

**Comment by nelkor** [comment]
> А зачем проверять есть ли ошибки, если можно сразу их исправить?

Во-первых, не все ошибки могут быть исправлены автоматически. Во-вторых, разработчик должен видеть то, что он коммитит. Если он видит один код, а прекоммит исправляет его на другой код и отправляет в Гитхаб — это плохо)
