### ISSUE TITLE
:wrench: Make Stylelint work

### ISSUE THREAD

**Issue by nelkor** [nelkor/passcryptum#45]
Suddenly it turned out that commands such as `npm run lint` and `npm run fix` do not pay attention to SCSS files. Although it seems that they should! These commands access `stylelint` and we have a `.stylelintrc` configuration file.

We are looking for a hero who can figure out what the problem is and fix it.

**Comment by antongospod** [comment]
Simply add to your package.json scripts `"lint:css": "stylelint \"src/**/*.{vue,scss,css}\"",`

**Comment by nelkor** [comment]
In general, we have calls to stylelint in lint and fix scripts. It turned out that stylelint just doesn't know how to fix some things. For example, spaces before a semicolon or extra indentation. So there is no need to fix it, it works as best as it can. For a clean fix of SCSS files, we can simply run Prettier.

Thank you @antongospod.
